apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: my-app
  ports:
    - name: web
      port: 80
      targetPort: 5000
    - name: metrics
      port: 8000
      targetPort: 8000
  type: LoadBalancer