apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-app-monitor
  labels:
    release: monitoring  # <--- This matches your kubectl output exactly
spec:
  selector:
    matchLabels:
      app: my-app        # <--- Make sure this matches the 'app' label in your Service.yaml
  endpoints:
  - port: metrics        # <--- This must match the 'name' given to the port in Service.yaml
    path: /metrics
    interval: 15s