apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-app-monitor
  labels:
    release: monitoring
spec:
  # --- ADD THIS SECTION ---
  namespaceSelector:
    any: true 
  # -------------------------
  selector:
    matchLabels:
      app: my-app
  endpoints:
  - port: metrics
    path: /metrics